pebble/clay

README.md
+ added example for loading a different config based on platform
=> Made documentation less ambiguous about classes

README.md
Thanks to @gregoiresage for pointing it out in #37
=> Moved the conversion information from `Clay.getSettings` to `ClayConfg.getSettings`

src/scripts/lib/clay-item.js, src/templates/components/checkboxgroup.tpl, src/templates/components/radiogroup.tpl, test/spec/components/index.js
=> Fix events firing on wrong element for button component

README.md, dev/custom-fn.js, dev/dev.js, gulpfile.js, index.js, package.json, test/fixture.js, test/spec/index.js
=> #20/allow user data

README.md, dev/config-2.js, dev/custom-fn.js, dev/dev.js, src/scripts/lib/clay-config.js, test/spec/lib/clay-config.js
=> #76/wipe page on build

dev/config.js, src/styles/clay/components/input.scss
=> fix styling of time and date fields on iOS

src/styles/clay/components/select.scss
=> fix styling of selects on windows

README.md, dev/config.js, src/templates/components/select.tpl, test/spec/components/select.js
=> Add optgroup to selects

src/scripts/lib/clay-config.js, test/spec/lib/clay-config.js
=> Only send settings that are actually in the config back to the watch

README.md, dev/config.js, dev/dev.js, src/scripts/lib/clay-config.js, src/scripts/lib/utils.js, test/spec/lib/clay-config.js
=> Add the option to only show items with particular capabilities

README.md, src/scripts/lib/utils.js, test/spec/.eslintrc, test/spec/lib/clay-config.js
=> Allow `NOT_` prefix for capabilities

README.md
=> Remove reference to "attributes" from docs

README.md
=> Add JS settings to getting started

README.md, index.js, test/spec/index.js
=> Expose Clay version

.gitignore, index.js, test/spec/index.js
=> Allow response in webviewclosed event to optionally be URI encoded

.eslintignore, README.md, dev/config-2.js, dev/config.js, dev/custom-fn.js, gulpfile.js, index.js, src/scripts/components/checkboxgroup.js, src/scripts/lib/clay-config.js, src/scripts/lib/clay-item.js, src/scripts/lib/manipulators.js, src/templates/components/checkboxgroup.tpl, test/fixture.js, test/karma.conf.js, test/spec/index.js, test/spec/lib/clay-config.js, test/spec/lib/clay-item.js, test/spec/lib/manipulators.js
=> #90/support message keys

README.md, index.js
=> #110/add get settings to migration guide

README.md
=> Add Configurable should be checked to cloudpebble getting started

gulpfile.js
=> Fixed `Error: Cannot find module 'message_keys'` in dev script

src/scripts/components/color.js, test/spec/components/color.js
=> Fix colorpicker for Diorite

README.md, package.json
=> Add 'configurable' capability

README.md
=> Use index.js not app.js in docs

dev/config.js, src/scripts/lib/clay-config.js
=> #151 - Fix incorrect value being set when `defaultValue` is falsey
